pipeline {
    agent any
    parameters {
        string(defaultValue: "name", description: "deployment name?", name: "choice3")  // Corrected the syntax
        choice(choices: ["TEST", "Dev", "QA", "PRE-PROD", "PROD"], description: "Which az?", name: "deployEnv")
        booleanParam(defaultValue: false, description: "Enable service?", name: "myBoolean")
    }
    stages {
        stage("stage1") {
            steps {
                echo "string is set to: ${params.choice3}\n"
            }
        }
        stage("stage2") {
            steps {
                echo "booleanParam is set to: ${params.myBoolean}\n"
            }
        }
        stage("stage3") {
            steps {
                echo "choice is set to: ${params.deployEnv}\n"  // Fixed the escape sequence for newline
            }
        }
    }
}
